### ISSUE TITLE
Missing translation string for YouTube embed

### ISSUE THREAD

**Issue by Madis0** [IMB11/fabulously-web#17]
Should be `https://www.youtube.com/watch?v=bb8G9X5Q_4I`

**Comment by IMB11** [comment]
Not sure I understand? You cant translate the iframe source URL

**Comment by Madis0** [comment]
Well... why not? Can't iframe update be hooked to a language change event in JS?

**Comment by Madis0** [comment]
https://github.com/Fabulously-Optimized/fabulously-web/commit/8bd90d2c8a3936c1a228e23da6fec39c852a6a68
