### ISSUE TITLE
Simplify language addition

### ISSUE THREAD

**Issue by Madis0** [IMB11/fabulously-web#34]
After #31 is done

Is it even necessary to define the languages in a separate file, instead of just adding more language files?

If yes, could the manifest be simplified at least - language name to be inside the language file and language code inherited from filename or also inside the file?

**Comment by IMB11** [comment]
I could take a look at making the language file thing dynamic, but i wouldn't be surprised if it's not possible due to Vite being static.

**Comment by IMB11** [comment]
Will work off #32
